force-app/main/default/objects/Annual_Inspection__c.object
<CustomObject>
    <description>Custom object to track annual inspections related to Property Management Fee Lands SOP AND Easement/Deed Restriction Monitoring Reports.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Monitoring status as of monitoring report completion date.  Should copy back to status at last monitoring on the associated interest when reporting is done.</description>
        <inlineHelpText>Select the final status of monitoring/compliance of the property interest at the end of reporting cycle OR leave as DRAFT to save the report and return later to complete.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Monitoring_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Annual Inspection/Monitoring</label>
    <nameField>
        <displayFormat>AI-{0000}-{MM}-{DD}-{YYYY}</displayFormat>
        <label>Annual Inspection/Monitoring</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Inspections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Monitoring_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Violation</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Not Evaluated</fullName>
    </customValue>
    <customValue>
        <fullName>Other or Historic</fullName>
    </customValue>
    <description>Created for status on the Easement monitoring reports and for status at last monitoring on the interest.</description>
    <masterLabel>Monitoring Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConvertToBoxFileTest.cls
/*
ConvertToBoxFile no longer in use: replaced by Process Builder/PDFGeneratorController2.apxc.
*/

//Test class that inserts an attachment to an Annual Inspection record

@isTest
public class ConvertToBoxFileTest {
	static testMethod void testMyController() {
        PageReference pageRef = new PageReference('/apex/MonitoringReportPDF?Id=');
        Test.setCurrentPage(pageRef);
        
        // Create new instance of an Annual Inspection        
        Annual_Inspection__c AI = new Annual_Inspection__c(Status__c = 'Draft', RecordTypeID = '012a0000001CH0F');
        insert AI;
        
        // Adds the id of the inserted project to the page
        ApexPages.currentPage().getParameters().put('Id', AI.Id);
        
        // Create attachment
        Attachment attach = new Attachment();
        
        // Set test fields for attachment
        attach.description = 'Test Description';
        attach.Name = 'TestName.txt';
        attach.Body = Blob.valueOf(' ');
        attach.ParentId = AI.Id;
        
        insert attach;
       
    }
}