force-app/main/default/objects/Annual_Inspection__c.object
<CustomObject>
    <description>Custom object to track annual inspections related to Property Management Fee Lands SOP AND Easement/Deed Restriction Monitoring Reports.</description>
    <fields>
        <fullName>Inspection_Date__c</fullName>
        <inlineHelpText>Select the last date of the inspection or monitoring on this property that is covered by this report.  If there were prior inspection dates, please enter them in the visit section below.</inlineHelpText>
        <label>Inspection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property_Interest__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Created to relate easement monitoring reports to the property interest level.  Fee inspections are at the PMU level.</description>
        <inlineHelpText>Select the easement or deed restriction to be monitored.</inlineHelpText>
        <label>Property Interest</label>
        <referenceTo>Property_Interest__c</referenceTo>
        <relationshipLabel>Easement/Deed Restriction Monitoring Reports</relationshipLabel>
        <relationshipName>Annual_Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Management_EDR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created to have a separate related list for easement/deed restriction monitoring reports on the property management unit record.</description>
        <inlineHelpText>Read only. Copied from the interest record when report is created.</inlineHelpText>
        <label>Property Management EDR</label>
        <referenceTo>Property_Management__c</referenceTo>
        <relationshipLabel>Easement/Deed Restriction Monitoring Reports</relationshipLabel>
        <relationshipName>Annual_Inspections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Management__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup field - Property Management Unit that you are inspecting</inlineHelpText>
        <label>Property Management</label>
        <referenceTo>Property_Management__c</referenceTo>
        <relationshipLabel>Annual Fee Inspections</relationshipLabel>
        <relationshipName>Compliance_Monitoring</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Monitoring status as of monitoring report completion date.  Should copy back to status at last monitoring on the associated interest when reporting is done.</description>
        <inlineHelpText>Select the final status of monitoring/compliance of the property interest at the end of reporting cycle OR leave as DRAFT to save the report and return later to complete.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Monitoring_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Annual Inspection/Monitoring</label>
    <nameField>
        <displayFormat>AI-{0000}-{MM}-{DD}-{YYYY}</displayFormat>
        <label>Annual Inspection/Monitoring</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Inspections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/box__FRUP__c.object
<CustomObject>
    <fields>
        <fullName>Manually_Set_Role__c</fullName>
        <inlineHelpText>Override the current role for this user using the dropdown list. The value in this field will move to the Role field once it has been updated in Box.</inlineHelpText>
        <label>Manually Set Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Box_Collaboration_Roles</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Property_Interest__c.object
<CustomObject>
    <description>Properties, rights or easements/deed restrictions related to management units in Property Management.</description>
    <fields>
        <fullName>Create_Box_Folders__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Creates box folders via process builder/apex. Primary References, Monitoring Documentation, and Older Monitoring Reports.</inlineHelpText>
        <label>Create Box Folders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRFolderID__c</fullName>
        <inlineHelpText>Box ID for Reports Archive Folder</inlineHelpText>
        <label>Reports Archive Folder ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Interest_Group__c</fullName>
        <inlineHelpText>Property and/or interest grouping with which this interest is associated.
Fee properties belong in fee management groupings.
Easements and deed restrictions go in partial interest groupings.</inlineHelpText>
        <label>Property Interest Group</label>
        <referenceTo>Property_Management__c</referenceTo>
        <relationshipLabel>Property Interests</relationshipLabel>
        <relationshipName>Related_Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Property Interest</label>
    <nameField>
        <label>Property Interest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Management__c.object
<CustomObject>
    <customHelpPage>Property_Management_Help</customHelpPage>
    <description>Tab dedicated to track property management units and their related property interests, contracts, payment information and other activities on property managed by TNC.</description>
    <fields>
        <fullName>Ecoregion__c</fullName>
        <label>Ecoregion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ecoregion_Global</valueSetName>
        </valueSet>
    </fields>
    <label>Property Management</label>
    <nameField>
        <label>Property Interest Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Management</pluralLabel>
    <recordTypes>
        <fullName>PMU</fullName>
        <active>true</active>
        <description>Property Management Unit - Inactive but cant remove from all profiles as default</description>
        <label>PMU</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Box_Collaboration_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Editor</fullName>
    </customValue>
    <customValue>
        <fullName>Viewer Uploader</fullName>
    </customValue>
    <customValue>
        <fullName>Previewer Uploader</fullName>
    </customValue>
    <customValue>
        <fullName>Viewer</fullName>
    </customValue>
    <customValue>
        <fullName>Previewer</fullName>
    </customValue>
    <customValue>
        <fullName>Uploader</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Owner</fullName>
    </customValue>
    <masterLabel>Box Collaboration Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Ecoregion_Global.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Asia Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Great Basin</fullName>
    </customValue>
    <customValue>
        <fullName>Great Central Valley</fullName>
    </customValue>
    <customValue>
        <fullName>Klamath</fullName>
    </customValue>
    <customValue>
        <fullName>Modoc Columbia Plateau</fullName>
    </customValue>
    <customValue>
        <fullName>Mojave Desert</fullName>
    </customValue>
    <customValue>
        <fullName>North Coast</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Current</fullName>
    </customValue>
    <customValue>
        <fullName>Sierra Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>Sonoran Desert</fullName>
    </customValue>
    <customValue>
        <fullName>South Coast</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Current</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
    </customValue>
    <customValue>
        <fullName>CA Central Coast</fullName>
    </customValue>
    <customValue>
        <fullName>Mojave Desesrt</fullName>
        <isActive>false</isActive>
        <label>Mojave Desesrt</label>
    </customValue>
    <customValue>
        <fullName>Central Coast</fullName>
        <isActive>false</isActive>
        <label>Central Coast</label>
    </customValue>
    <customValue>
        <fullName>CA South Coast</fullName>
        <isActive>false</isActive>
        <label>CA South Coast</label>
    </customValue>
    <customValue>
        <fullName>CA Mojave</fullName>
        <isActive>false</isActive>
        <label>CA Mojave</label>
    </customValue>
    <description>Promoted from Property Management Object</description>
    <masterLabel>Ecoregion</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Monitoring_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Violation</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Not Evaluated</fullName>
    </customValue>
    <customValue>
        <fullName>Other or Historic</fullName>
    </customValue>
    <description>Created for status on the Easement monitoring reports and for status at last monitoring on the interest.</description>
    <masterLabel>Monitoring Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/*
Written By: Katharine Anderson
Last Updated: 12-19-2018
Purpose: Call these methods from test classes to create records to test against. Best practice as recommended 
by Salesforce. Add methods as needed for records of different objects.
*/

@isTest
public class TestDataFactory {
    
    public static List<Property_Management__c> createPropertyManagement (Integer numPMs){
        List<Property_Management__c> pmList = new List<Property_Management__c>();
        For (integer i=0; i < numPMs; i++){
            Property_Management__c PM = new Property_Management__c();
            PM = new Property_Management__c();
            PM.RecordTypeId = '0120c0000018JQW';
            PM.Name = 'Test' + i;
            PM.Ecoregion__c = 'TEST';
            pmList.add(PM);
        }
        insert pmList;
        system.assert(pmList.size() == numPMs, '***System Assert: ' +pmList.size() + ' records inserted, ' + numPMs + 'records expected.');
        return pmList;
    }
    
    public static List<Property_Interest__c> createPropertyInterests (Integer numPMs, Integer numPIs){
        List<Property_Management__c> pmList = TestDataFactory.createPropertyManagement(numPMs);
        List<Property_Interest__c> piList = new List<Property_Interest__c>();
        for (integer j=0; j < pmList.size(); j++){
            Property_Management__c pmu = pmList[j];
            for (integer k = 0; k < numPIs ; k++) {
                Property_Interest__c PI = new Property_Interest__c();
                PI.RecordTypeID = '012a0000001CGoS';
                PI.MRFolderID__c = '0000000000';
                PI.Property_Interest_Group__c = pmu.id;
                PI.Create_Box_Folders__c = false;
                PI.Name = 'TEST' + k;
                piList.add(PI);
            }
        }
        insert piList;
        system.assert(piList.size() == (numPIs*numPMs), '***System Assert: ' +piList.size() + ' records inserted, ' + (numPIs*numPMs) + 'records expected.');
        return piList;
    }
        
    public static List<Annual_Inspection__c> createAnnualInspections (Integer numPMs, Integer numPIs, Integer numAIs) {
        List<Property_Interest__c> piList = TestDataFactory.createPropertyInterests(numPMs, numPIs);        
        List<Annual_Inspection__c> aiList = new List<Annual_Inspection__c>();
        for (integer l=0; l < piList.size() ; l++ ){
            Property_Interest__c pir = piList[l];
            for(integer m = 0; m < numAIs ; m++){
                Annual_Inspection__c AI = new Annual_Inspection__c();
                AI.Status__c = 'Draft';
                AI.RecordTypeID = '012a0000001CH0F';
                AI.Property_Management_EDR__c = pir.Property_Interest_Group__c;
                AI.Property_Interest__c = pir.id;
                AI.Inspection_Date__c = Date.newInstance(2016, 12, 9);
                aiList.add(AI);
            }      
        }
        insert aiList;
        system.assert(aiList.size() == (numAIs*numPIs*numPMs), '***System Assert: ' +aiList.size() + ' records inserted, ' + (numAIs*numPIs*numPMs) + 'records expected.');
        return aiList;
    }
    public static List<box__FRUP__c> createFRUP (Integer numFRUPs){
        List<box__FRUP__c> frupList = new List<box__FRUP__c>();
        For (integer i=0; i < numFRUPs; i++){
    		box__FRUP__c frup = new box__FRUP__c();
    		frup.box__Object_Name__c = 'Property_Interest__c';
        	frup.box__Permission__c = 'Read/Write';
            frup.Manually_Set_Role__c = 'Viewer Uploader';
            frup.box__CollaborationID__c = '791293';
            frupList.add(frup);
        }
        insert frupList;
        system.assert(frupList.size() == numFRUPs, '***System Assert: ' +frupList.size() + ' records inserted, ' + numFRUPs + 'records expected.');
        return frupList;
    }    

}