force-app/main/default/objects/Bid__c.object
<CustomObject>
    <description>Record that tracks bid information. Created for Migratory Bird Initiative team for their reverse auction work in 2013.</description>
    <label>Bid</label>
    <nameField>
        <label>Bid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bird_Returns_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Contracts_List_View__c</fullName>
        <label>Contracts List View</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Bird Returns Setting</label>
</CustomObject>

force-app/main/default/objects/Bird_Returns_Site_Compliance_Visit__c.object
<CustomObject>
    <description>Records overall site data for compliance site visits in the Bird Returns program.</description>
    <fields>
        <fullName>Bid_ID__c</fullName>
        <description>The Contract that this Site Compliance Visit is for.</description>
        <inlineHelpText>Lookup to the contract associated with this site compliance visit.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Site Compliance VIsits</relationshipLabel>
        <relationshipName>Site_Compliance_VIsits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reporter_Type__c</fullName>
        <description>Used to filter the roll-up summaries that calculate final compliance numbers.</description>
        <inlineHelpText>Indicates if the reporter is a field tech (who submitted a report via iForm) or a self reporter who submitted a report at http://birdreturns.org/report-water-depth/.</inlineHelpText>
        <label>Reporter Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self-reporter</fullName>
                </value>
                <value>
                    <fullName>Field Tech reporter</fullName>
                    <default>true</default>
                    <label>Field Tech reporter</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Site Compliance Visit</label>
    <nameField>
        <displayFormat>SCV-{000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Compliance Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bird_Returns_Stake__c.object
<CustomObject>
    <description>Represents a specific stake on a site involved in the Bird Returns program.</description>
    <fields>
        <fullName>Bid_ID__c</fullName>
        <formula>Contract_ID__r.BirdReturns_Bid_Name__r.Name</formula>
        <inlineHelpText>Pulls in the Bid ID for this stake.</inlineHelpText>
        <label>Bid ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_ID__c</fullName>
        <description>The contract that this stake is associated with.</description>
        <inlineHelpText>The contract that this stake is associated with. (Lookup field).</inlineHelpText>
        <label>Contract ID</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Stakes</relationshipLabel>
        <relationshipName>Stakes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stake</label>
    <nameField>
        <label>Stake Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BirdReturns_Bid_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the &quot;Look Up&quot; icon to search for the correct Bid Name. Enter the full bid name, including program period. Format: &quot;16-FR-055&quot;.</inlineHelpText>
        <label>BirdReturns Bid Name</label>
        <referenceTo>Bid__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/contractListBirdReturns.cls
global class contractListBirdReturns {
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT Id, BirdReturns_Bid_Name__r.Name FROM Contract]));
                setCon.setPageSize(1000);
            }
            if(!Test.isRunningTest()){
                setCon.setFilterId(Bird_Returns_Setting__c.getInstance().Contracts_List_View__c);
            }
            return setCon;
        }
        set;
    }
    public List<Contract> getContracts() {
        return (List<Contract>) setCon.getRecords();
    }
    
    @RemoteAction
    global static Id createStake(String lat, String lng, Id contractId) {
        List<Integer> stakeNames = new List<Integer>();
        for(Bird_Returns_Stake__c contractStake : [SELECT Id,Name
                                                      FROM Bird_Returns_Stake__c
                                                      WHERE Contract_Id__c =: contractId]) {
            stakeNames.add(Integer.valueOf(contractStake.Name));
        }

        stakeNames.sort();

        // the index of the last element in the list is size - 1. we then add 1 to THE VALUE to get the new name
        
        Integer newName;

        if(stakeNames.size()==0){
            newName = 1;
        } else {
             newName = stakeNames.get(stakeNames.size() - 1) + 1;
        }
        

        Bird_Returns_Stake__c stake = new Bird_Returns_Stake__c(Contract_Id__c = contractId, Name = String.valueOf(newName));
        stake.Stake_Location__latitude__s = Double.valueOf(lat);
        stake.Stake_Location__longitude__s = Double.valueOf(lng);
        insert stake;
        return stake.Id;
    }

    @RemoteAction
    global static Id createSCV(Id contractId) {
        List<Bird_Returns_Site_Compliance_Visit__c> scvstoday = [Select ID 
                                                                FROM Bird_Returns_Site_Compliance_Visit__c 
                                                                WHERE Bid_Id__c =: contractId
                                                                AND Visit_Date__c = TODAY 
                                                                AND Reporter_Type__c = 'Field Tech reporter'
                                                                LIMIT 1];
        if(scvstoday.size() == 0) {
            Bird_Returns_Site_Compliance_Visit__c scv = new Bird_Returns_Site_Compliance_Visit__c(Bid_Id__c = contractId);
            insert scv;
            return scv.Id;
        }
        return scvstoday[0].Id;
    }
}