force-app/main/default/objects/Contract_Amendment__c.object
<CustomObject>
    <description>Custom object to track real estate and non-real estate contract amendments.</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Amendments</relationshipLabel>
        <relationshipName>R00N300000024l3OEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Extend_Contract_End_Date__c</fullName>
        <label>Extend Contract End Date?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Contract_End_Date__c</fullName>
        <inlineHelpText>If your contract amendment includes a calendar expiration or end date, enter that here. Some examples: leases, purchases or time-frame specific consulting.</inlineHelpText>
        <label>New Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Operations__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If applicable, please select the name of the Operations Partner who is required to review and approve the contract. Operations approval not required for Grant-in amendments.</inlineHelpText>
        <label>Operations</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected user is not an Operations Manager. Please consult with your regional Operations Manager on whom to select.</errorMessage>
            <filterItems>
                <field>User.Department</field>
                <operation>contains</operation>
                <value>Operations</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002OzLYEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Executed Amendment</fullName>
                </value>
                <value>
                    <fullName>Application Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Amendment</label>
    <nameField>
        <displayFormat>Amendment-{MM}{DD}{YYYY}-{00}</displayFormat>
        <label>Contract Amendment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/testTriggers.cls
public class testTriggers {
	public static testmethod void test_UpdateContractEndDate() {
		
		Account a = new Account(Name='Deepak Apex Test Account', Type='Nonprofit', Website='http://www.test.com/');
		insert a;
		Account reta = [select id, Name from Account where id=:a.id][0];
		System.assertEquals(a.Id, reta.id);
		System.assertEquals('Deepak Apex Test Account', reta.Name);

		Contract c = new Contract(Name='Deepak Apex Test Contract', AccountId=a.Id, Description='Test Desc', OwnerExpirationNotice = '60', EndDate = date.newInstance(2006,01,01));
		insert c;
		Contract retc = [select id, Name, ContractNumber from Contract where id=:c.id][0];
		System.assertEquals(c.Id, retc.id);
		System.assertEquals('Deepak Apex Test Contract', retc.Name);
		

		
		Contract_Amendment__c ca = new Contract_Amendment__c(Contract_Number__c=c.Id, Status__c='Approved', Extend_Contract_End_Date__c = 'Yes', New_Contract_End_Date__c = Date.valueOf('2008-12-31'), Operations__c = UserInfo.getUserId() );
		insert ca;
		Contract_Amendment__c retca = [select id, Contract_Number__c from Contract_Amendment__c where id=:ca.id][0];
		System.assertEquals(ca.Id, retca.id);
		System.assertEquals(c.Id, retca.Contract_Number__c);
		
		Set<Id> contractAmendIdSet = new Set<Id>();
		contractAmendIdSet.add(retca.Id);
		

		Map<Id, Contract_Amendment__c> contractAmendMap = new Map<Id, Contract_Amendment__c>(
			[select Id, Contract_Number__c, Status__c, Extend_Contract_End_Date__c, New_Contract_End_Date__c  from Contract_Amendment__c where Id in :contractAmendIdSet]);
		
		Set<Id> contractIdSet = new Set<Id>();
		if (contractAmendMap.containsKey(retca.Id)) {
			Contract_Amendment__c contractAmendObj = contractAmendMap.get(retca.Id);
			// Only if Contract Amendment has Extend Contract End Date = Yes and Status = Approved
			// Then adding it to the list 
			if(contractAmendObj!=null && 
				contractAmendObj.Status__c=='Approved' && 
				contractAmendObj.Extend_Contract_End_Date__c=='Yes') {
				contractIdSet.add(contractAmendObj.Contract_Number__c);
			}
		}
		

		Map<Id, Contract> contractMap = new Map<Id, Contract>(
			[select Id, ContractNumber, EndDate  from Contract where Id in :contractIdSet]);
		
		List<Contract> contractList = new List<Contract>();
		
		if (contractAmendMap.containsKey(retca.Id)) {
			Contract_Amendment__c contractAmendObj = contractAmendMap.get(retca.Id);
			if(contractAmendObj.Contract_Number__c!=null && 
				contractMap.containsKey(contractAmendObj.Contract_Number__c)){
				Contract ct = contractMap.get(contractAmendObj.Contract_Number__c);
				ct.EndDate = contractAmendObj.New_Contract_End_Date__c;
				contractList.add(ct);
			}
		}
		
		if(contractList.size() >0){
			update contractList;
		}		
		
	}
}